help :-
        write('Ketik perintah sebagai berikut'),nl,
        write('0. start -> Memulai game'),nl,
        write('1. w -> '),
        write('geser atas'),nl,
        write('2. a -> '),
        write('geser kiri'),nl,
        write('3. s -> '),
        write('geser bawah'),nl,
        write('4. d -> '),
        write('geser kanan'),nl,
        write('5. map -> Menampilkan peta'),nl,
        write('6. inventory -> Menampilkan inventarismu'),nl,
        write('7. equipment -> Menampilkan equipment'),nl,
        write('8. status -> Menampilkan kondisi pemain'),nl,
        write('9. answer -> Menyelesaikan gawe'),nl,
        write('10. cheat -> Menyelesaikan gawe tapi lebih efektif'),nl,
        write('11. pray -> Minta bantu ke kekuatan dari atas'),nl,
        write('12. sekip -> Lari dari gawe'),nl,
        write('13. sleep -> Tidur'),nl,
        write('14. shop -> Mengakses toko'),nl,
        write('15. assign -> Meminta quest'),nl,
        write('16. fAss -> Mengerjakan TA, hanya bisa di L'),nl,
        write('17. help -> Menampilkan ini'),nl,
        write('18. save(Filename) -> Menyimpan game'),nl,
        write('19. load_game(Filename) -> Meload game'),nl,
        write('20. exit -> Keluar dari game'),nl,!.