help :-
        write('Ketik perintah sebagai berikum'),nl,
        write('0. start'),
        write('1. w -> '),
        write('geser atas'),nl,
        write('2. a -> '),
        write('geser kiri'),nl,
        write('3. s -> '),
        write('geser bawah'),nl,
        write('4. d -> '),
        write('geser kanan'),nl,
        write('5. map'),nl,
        write('6. inventory'),nl,
        write('7. answer'),nl,
        write('8. cheat'),nl,
        write('9. pray'),nl,
        write('10. sekip'),nl,
        write('11. sleep'),nl,
        write('12. shop'),nl,
        write('13. assign'),nl,
        write('14. save(nama_file)'),nl,
        write('15. load(nama_file)'),nl,
        write('16. help'),nl,
        write('17. exit'),nl,!.